---
title: "QTL-SRS"
author: "Marcos Mancilla"
date: "16/10/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(graphics)
library(psych)
library(stats)
library(dplyr)
library(tidyr)
library(ggplot2)
```

```{r}
dat <- read_excel("dataset2.XLS")
summary(dat)
head(dat)
str(dat)
```

```{r}
ggplot(dat, aes(x = Biomasa_kg)) +
  geom_histogram()
```

```{r}
ggplot(dat, aes(x = Mortalidad)) +
  geom_histogram()+ scale_x_continuous(limit = c(0,200))+ scale_y_continuous(limit = c(0,2000))
```

```{r, include=TRUE, echo=FALSE}
ggplot(dat, aes(x = Mortalidad_Biomasa_kg)) +
  geom_histogram()+ scale_x_continuous(limit = c(0,200))+ scale_y_continuous(limit = c(0,2000))
```

```{r}
par(mfrow=c(1,2))
hist(dat$Biomasa_kg, col="light blue", main = "Histograma Biomasa", xlab = "Biomasa (kg)")
boxplot(dat$Biomasa_kg, col="light blue", main = "Boxplot Biomasa", ylab = "Biomasa (kg)")
```

```{r}
par(mfrow=c(1,2))
hist(dat$Mortalidad, col="light blue", main = "Histograma Mortalidad", xlab = "Mortalidad (n°)", 
     xlim = c(0, 2000),
     ylim = c(0, 10000))
boxplot(dat$Mortalidad, col="light blue", main = "Boxplot Mortalidad", ylab = "Mortalidad (n°)")
```

```{r}
table(dat$Subgrupo)
table(dat$Centro)
dat$Centro <- as.factor(dat$Centro)
dat$Subgrupo <- as.factor(dat$Subgrupo)
str(dat)
summary(dat)
```

```{r}
table(dat$Subgrupo,dat$Centro)
tabla1 <- with(dat,table(Subgrupo,Centro))
prop.table(tabla1)
tabla1_prop <- with(dat,prop.table(tabla1))
knitr::kable(tabla1_prop,caption ="Proporción datos por Subgrupo de peces en diferentes Centros")
```

Los datos no están balanceados. Hay más observaciones para el Subgrupo QTL2 (70,7%) que para otros subgrupos. El Subgrupo en menor proporción es el SQTL que está presente solo en Centro C.
```{r}
Table <- dat %>%
  filter(Centro == "1")%>%
  summarize("Máximo"=max(N_peces), "Mínimo"=min(N_peces))

knitr::kable(Table, caption = "Tabla 2. Datos Subgrupo 1")
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```